name: 'Jest Coverage Diff'
description: 'A github action to comment jest coverage diff on a PR'
author: 'Anuraag Puri'
inputs:
  accessToken:
    description: 'access token required to comment on a pr'
    default: ${{ github.token }}
  prNumber:
    description: 'PR number e.g. 789'
  branchNameBase:
    description: 'The branch the pr wants to merge into e.g. main'
  branchNameHead:
    description: 'The branch the pr is requesting review on'
  coverageReportUrl:
    description: 'URL to download the coverage report artifact'
  fullCoverageDiff:
    description: 'get the full coverage with diff or only the diff'
    default: false
  runCommand:
    description: 'custom command to get json-summary'
  afterSwitchCommand:
    description: 'command to run after switching to default branch'
    default: null
  delta:
    description: 'Percent difference in any file"s coverage at which to fail the job e.g. 1'
    default: null
  totalDelta:
    description: 'Percent difference in total codebase coverage at which to fail the job e.g. 1'
    default: null
  useSameComment:
    description: 'While commenting on the PR update the existing comment'
    default: true
branding:
  color: red
  icon: git-pull-request
runs:
  using: 'node12'
  main: 'dist/index.js'
