name: 'Jest Coverage Diff'
description: 'A github action to comment jest coverage diff on a PR'
author: 'Anuraag Puri'
inputs:
  accessToken:
    description: 'access token required to comment on a pr'
    default: ${{ github.token }}
  prNumber:
    description: 'PR number e.g. 789'

  coverageReportUrl:
    description: 'URL to download the coverage report artifact'
    default: ''
  coverageReportExpiry:
    description: 'Expiry datetime for coverage report artifact'
    default: ''
  runCommand:
    description: 'custom command to get json-summary'
    default: ''
  afterSwitchCommand:
    description: 'command to run after switching to default branch'
    default: ''

  useSameComment:
    description: 'While commenting on the PR update the existing comment'
    default: true
  fullCoverageDiff:
    description: 'get the full coverage with diff or only the diff'
    default: false

  delta:
    description: 'Percent difference in any file"s coverage at which to fail the job e.g. 1'
    default: ''
  totalDelta:
    description: 'Percent difference in total codebase coverage at which to fail the job e.g. 1'
    default: ''
branding:
  color: red
  icon: git-pull-request
runs:
  using: 'node12'
  main: 'dist/index.js'
